'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Alterar1

    '''<summary>
    '''div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cod_lancamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cod_lancamento As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''acao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acao As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''LbResultado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LbResultado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cod_despesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cod_despesa As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''v_cod_despesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents v_cod_despesa As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cod_ano control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cod_ano As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''v_cod_ano control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents v_cod_ano As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''cod_mes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cod_mes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''v_cod_mes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents v_cod_mes As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''dt_vencimento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt_vencimento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''v_dt_vencimento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents v_dt_vencimento As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''txt_valor_despesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_valor_despesa As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''v_txt_valor_despesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents v_txt_valor_despesa As Global.System.Web.UI.WebControls.RequiredFieldValidator

    '''<summary>
    '''dt_pagamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dt_pagamento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_valor_pagamento control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_valor_pagamento As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_descricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_descricao As Global.System.Web.UI.HtmlControls.HtmlTextArea

    '''<summary>
    '''btn_alterar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_alterar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_excluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_excluir As Global.System.Web.UI.WebControls.Button
End Class
