'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Visualizar

    '''<summary>
    '''lbExibir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbExibir As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''div control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cod_despesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cod_despesa As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''acao_confirma control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents acao_confirma As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''LbResultado control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LbResultado As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_despesa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_despesa As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_descricao control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_descricao As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btn_ativar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_ativar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_excluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_excluir As Global.System.Web.UI.WebControls.Button
End Class
